/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import consulta.consulta;
import controlador.ctlClientes;
import controlador.ctlDepartamentos;
import controlador.ctlEstados;
import controlador.ctlGeneros;
import controlador.ctlTecnicos;
import controlador.ctlTickets;
import controlador.ctlUsuarios;
import modelo.clientes;
import modelo.departamentos;
import modelo.estados;
import modelo.generos;
import modelo.tecnicos;
import modelo.tickets;
import modelo.usuarios;

/**
 *
 * @author admin
 */
public class menuPri extends javax.swing.JFrame {

    frmTecnicos T = new frmTecnicos();
    frmTickets TI = new frmTickets();
    frmUsuarios U = new frmUsuarios();
    
    /**
     * Creates new form menuPri
     */
    public menuPri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTecnicos = new javax.swing.JButton();
        btnTickets = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnGenero = new javax.swing.JButton();
        btnDepartamentos = new javax.swing.JButton();
        btnEstados = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL");

        btnTecnicos.setText("Tecnicos");
        btnTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTecnicosActionPerformed(evt);
            }
        });

        btnTickets.setText("Tickets");
        btnTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketsActionPerformed(evt);
            }
        });

        btnUsuarios.setText("Usuarios del Sistema");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnGenero.setText("Mantenimiento Generos");
        btnGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneroActionPerformed(evt);
            }
        });

        btnDepartamentos.setText("Mantenimiento Departamentos");
        btnDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartamentosActionPerformed(evt);
            }
        });

        btnEstados.setText("Mantenimiento Estados");
        btnEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadosActionPerformed(evt);
            }
        });

        btnClientes.setText("Mantenimiento Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnGenero)
                        .addGap(93, 93, 93)
                        .addComponent(btnDepartamentos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnEstados)
                        .addGap(27, 27, 27)
                        .addComponent(btnClientes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnTecnicos)
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(btnTickets))
                        .addGap(47, 47, 47)
                        .addComponent(btnUsuarios)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenero)
                    .addComponent(btnDepartamentos))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstados)
                    .addComponent(btnClientes))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTecnicos)
                    .addComponent(btnTickets)
                    .addComponent(btnUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTecnicosActionPerformed
            
        frmTecnicos frmTecnicos = new frmTecnicos();
        consulta consulta = new consulta();
        tecnicos tTecnicos = new tecnicos();
        ctlTecnicos ctlTecnicos = new ctlTecnicos(tTecnicos, consulta, frmTecnicos);
        ctlTecnicos.iniciar();
        frmTecnicos.setVisible(true);

    }//GEN-LAST:event_btnTecnicosActionPerformed

    private void btnTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketsActionPerformed
        // TODO add your handling code here:
         frmTickets frmTickets = new frmTickets();
        consulta consulta = new consulta();
        tickets tTickets = new tickets();
       ctlTickets ctlTickets = new ctlTickets(tTickets, consulta, frmTickets);
        ctlTickets.iniciar();
        frmTickets.setVisible(true);
    }//GEN-LAST:event_btnTicketsActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        frmUsuarios frmUsuarios = new frmUsuarios();
        consulta consulta = new consulta();
        usuarios tUsuarios = new usuarios();
       ctlUsuarios ctlUsuarios = new ctlUsuarios(tUsuarios, consulta, frmUsuarios);
        ctlUsuarios.iniciar();
        frmUsuarios.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneroActionPerformed
        // TODO add your handling code here:
        frmGeneros frmGeneros = new frmGeneros();
        consulta consulta = new consulta();
        generos tGeneros = new generos();
        ctlGeneros ctlGeneros = new ctlGeneros(tGeneros, consulta, frmGeneros);
        ctlGeneros.iniciar();
        frmGeneros.setVisible(true);
    }//GEN-LAST:event_btnGeneroActionPerformed

    private void btnDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartamentosActionPerformed

        // TODO add your handling code here:
        frmDepartamentos frmDepartamentos = new frmDepartamentos();
        consulta consulta = new consulta();
        departamentos tDepartamentos = new departamentos();
        ctlDepartamentos ctlDepartamentos = new ctlDepartamentos(tDepartamentos, consulta, frmDepartamentos);
        ctlDepartamentos.iniciar();
        frmDepartamentos.setVisible(true);
    }//GEN-LAST:event_btnDepartamentosActionPerformed

    private void btnEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadosActionPerformed

        // TODO add your handling code here:
        
        frmEstados frmEstados = new frmEstados();
        consulta consulta = new consulta();
        estados tEstados = new estados();
        ctlEstados ctlEstados = new ctlEstados(tEstados, consulta, frmEstados);
        ctlEstados.iniciar();
        frmEstados.setVisible(true);
    }//GEN-LAST:event_btnEstadosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        frmClientes frmClientes = new frmClientes();
        consulta consulta = new consulta();
        clientes tClientes = new clientes();
        ctlClientes ctlClientes = new ctlClientes(tClientes, consulta, frmClientes);
        ctlClientes.iniciar();
        frmClientes.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        frmLogin frmLogin = new frmLogin();
        frmLogin.setVisible(true);
        frmLogin.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClientes;
    public javax.swing.JButton btnDepartamentos;
    public javax.swing.JButton btnEstados;
    public javax.swing.JButton btnGenero;
    private javax.swing.JButton btnTecnicos;
    private javax.swing.JButton btnTickets;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
